services:
  smart-door-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-door-server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /mnt/smart-door/database:/app/database
      - /mnt/smart-door/database/logs:/app/logs
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MQTT_BROKER_HOST=broker.emqx.io
      - MQTT_BROKER_PORT=1883
      - QWEN_API_BASE=http://qwen-ai:11434/v1
      - QWEN_MODEL_NAME=qwen2.5-coder:1.5b

    depends_on:
      - qdrant
      - qwen-ai

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - /mnt/smart-door/database/qdrant_storage:/qdrant/storage

  qwen-ai:
    image: ollama/ollama:latest
    container_name: qwen-ai-server
    restart: always
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_NUM_THREADS=10
    volumes:
      - /mnt/smart-door/ollama_storage:/root/.ollama






